[package]
name = "judge-grpc-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "judge-grpc-server"
path = "src/server.rs"

[[bin]]
name = "judge-grpc-client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.79"
prost = "0.12.3"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.14"
tonic = "0.10.2"

[build-dependencies]
anyhow = "1.0.79"
tonic-build = "0.10.2"
