name: Build

on:
  push:
    branches:
      - main

# Run on both Windows and Ubuntu
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release
          path: |
            target/release/judge-grpc-server(.exe)?
            target/release/judge-grpc-client(.exe)?
